coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: e-2-e 
      name: E2E
      paths:
        - backend/hellocucumber/**
    - component_id: be-unit-tests
      name: BE Unit Tests 
      paths:
        - backend/junit5-migration-maven/**
    - component_id: api 
      name: API
      paths:
        - backend/api/**
    - component_id: fe-unit-tests
      name: FE Unit Tests 
      paths:
        - ui/**
