flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90% 

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: react-testing-library  
      name: React Testing Library 
      paths:
        - ui/react-testing-library/**
    - component_id: react-main-library  
      name: React Main 
      paths:
        - ui/react-main/**