name: Generate Allure Report

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
            distribution: zulu
            java-version: '17'
          
      - name: Run Java tests
        working-directory: ./api/junit5-migration-maven
        run: mvn -B test

      - name: Run API tests
        working-directory: ./api/api
        run: mvn -B test
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies in main FE
        working-directory: ./ui/react-main
        run: npm install
          
      - name: Run tests in main fe
        working-directory: ./ui/react-main
        run: npx jest --coverage

      - name: Install dependencies in react library
        working-directory: ./ui/react-testing-library
        run: npm install

      - name: Run tests in react library
        working-directory: ./ui/react-testing-library
        run: npx jest --coverage
        
      - name: Upload fe reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

     
