name: Generate Allure Report

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
            distribution: zulu
            java-version: '17'
          
      - name: Run Java tests
        working-directory: ./api/junit5-migration-maven
        run: ./mvnw verify
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./ui/react-testing-library
        run: npm install

      - name: Run Jest tests
        working-directory: ./ui/react-testing-library
        run: npm test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: mgrybyk-org/allure-report-branch-js-action@v1.4.5
        if: always()
        continue-on-error: true
        id: allure
        with:
          report_id: 'pr-test'
          gh_pages: 'gh-pages'
          report_dir: 'allure-results'
          max_reports: 9

      - name: Git Commit and Push Action
        uses: mgrybyk-org/git-commit-pull-push-action@v1
        if: always()
        with:
          repository: gh-pages
          branch: gh-pages
          pull_args: --rebase -X ours
      
      - name: Comment PR with Allure Report link
        if: ${{ always() && github.event_name == 'pull_request' && steps.allure.outputs.report_url }}
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.allure.outputs.test_result_icon }} [Allure Report](${{ steps.allure.outputs.report_url }})
          comment_tag: allure_report
          mode: recreate

     